games/urls.py
from django.urls import path

from games.views import MathFactsView, AnagramHuntView, GameScoresView, LeaderboardView, record_score

app_name = 'games'
urlpatterns = [
    path('math-facts/', MathFactsView.as_view(), name='math-facts'),
    path('anagram-hunt/', AnagramHuntView.as_view(), name='anagram-hunt'),
    path('record-score/', record_score, name="record-score"),
    path('game-scores/', GameScoresView.as_view(), name="game-scores"),
    path('leaderboard/', LeaderboardView.as_view(), name="leaderboard")
]

play2learn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path('', include("games.urls")),
    path('', include('pages.urls')),
    path('contact/', include('contact.urls')),
    path('account/', include('allauth.urls')),
    path('account/', include('users.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from .views import ReviewCreateView, ReviewDeleteView, ReviewDetailView, ReviewListView, ReviewUpdateView

app_name = 'reviews'
urlpatterns = [
    path('review/<int:pk>/update/', ReviewUpdateView.as_view(), name='update'),
    path('review/create/', ReviewCreateView.as_view(), name='create'),
    path('', ReviewListView.as_view(), name='list'),
    path('review/<int:pk>/', ReviewDetailView.as_view(), name='detail'),
    path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='delete'),
]

reviews/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Review(models.Model):
    review = models.TextField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT
    )

    def get_absolute_url(self):
        return reverse('reviews:detail', args=[str(self.pk)])
    
    def __str__(self):
        return self.review

reviews/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from .models import Review
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

class ReviewCreateView(LoginRequiredMixin, CreateView):
    model = Review
    fields = ['review']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ReviewListView(ListView):
    model = Review

class ReviewDetailView(DetailView):
    model = Review

class ReviewUpdateView(UpdateView):
    model = Review
    fields = ['review']

class ReviewDeleteView(UserPassesTestMixin, DeleteView):
    model = Review
    success_url = reverse_lazy('reviews:list')

    def test_func(self):
        obj = self.get_object()
        return self.request.user == obj.user

templates/reviews/review_confirm_delete.html
{% extends "_base.html" %}

{% block title %}Delete Review{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 text-center"
    style="max-width: 30rem">
    <form method="post">
      {% csrf_token %}
      <p><strong>Are you sure you want to delete this review?</strong></p>
      <p>{{ review.review }}</p>
      <button class="btn btn-success form-control">Confirm</button>
    </form>
  </div>
{% endblock %}

templates/reviews/review_detail.html
{% extends "_base.html" %}

{% block title %}Review{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 text-center"
    style="max-width: 30rem">
    <div class="card-header">{{ review.review }}</div>
    {% if review.user == user %}
    <div class="card-footer">
        <a href="{% url 'reviews:update' review.pk %}"
          class="btn btn-info btn-sm me-2">Update</a>
        <a href="{% url 'reviews:delete' review.pk %}"
          class="btn btn-danger btn-sm me-2">Delete</a>
      </div>
      {% endif %}
      <small class="text-muted">
        Created on: {{ review.created }} by {{ review.user.username }} <br>
        Last updated: {{ review.updated }}
      </small>
    </div>
  </div>
{% endblock %}

templates/reviews/review_form.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add/Update Review{% endblock %}
{% block main %}
  <div class="card border-primary m-auto mb-3 p-3"
    style="max-width: 30rem">
    <form method="post">
      {% csrf_token %}
      <table class="table">
        {{ form|crispy }}
      </table>
      <button class="btn btn-success float-end">Submit</button>
    </form>
  </div>
{% endblock %}

templates/reviews/review_list.html
{% extends "_base.html" %}

{% block title %}Reviews{% endblock %}
{% block main %}
  {% if user.is_authenticated %}
  <a class="btn btn-success btn-sm float-end" href="{% url 'reviews:create' %}">
    + New Review
  </a>
  {% endif %}
  <h2>Reviews</h2>
  <ul class="list-group list-group-flush mb-3">
    {% for review in review_list %}
      <li class="list-group-item">
        <a href="{{ review.get_absolute_url }}">{{ review.review }}</a>
        {% if review.user == user %}
        <a href="{% url 'reviews:update' review.pk %}"
          class="btn btn-info btn-sm float-end me-2">Update</a>
        <a href="{% url 'reviews:delete' review.pk %}"
          class="btn btn-danger btn-sm float-end me-2">Delete</a>
        {% else %}
        <small>by {{ review.user.username }}</small>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}