contact/urls.py
from django.urls import path

from .views import ContactUsView, ContactUsThanksView

app_name = 'contact'
urlpatterns = [
    path('contact-us/', ContactUsView.as_view(), name='app'),
    path('contact-us/thanks/', ContactUsThanksView.as_view(), name='thanks'),
]

games/urls.py
from django.urls import path

from games.views import MathFactsView, AnagramHuntView, GameScoresView, LeaderboardView, record_score

app_name = 'games'
urlpatterns = [
    path('math-facts/', MathFactsView.as_view(), name='math-facts'),
    path('anagram-hunt/', AnagramHuntView.as_view(), name='anagram-hunt'),
    path('record-score/', record_score, name="record-score"),
    path('game-scores/', GameScoresView.as_view(), name="game-scores"),
    path('leaderboard/', LeaderboardView.as_view(), name="leaderboard")
]

pages/urls.py
from django.urls import path

from .views import AboutUsView, HomePageView

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),
]

play2learn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path("admin/", admin.site.urls),
    path('', include("games.urls")),
    path('', include('pages.urls')),
    path('contact/', include('contact.urls')),
    path('account/', include('allauth.urls')),
    path('account/', include('users.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from .views import ReviewCreateView, ReviewDeleteView, ReviewDetailView, ReviewListView, ReviewUpdateView

app_name = 'reviews'
urlpatterns = [
    path('review/<int:pk>/update/', ReviewUpdateView.as_view(), name='update'),
    path('review/create/', ReviewCreateView.as_view(), name='create'),
    path('', ReviewListView.as_view(), name='list'),
    path('review/<int:pk>/', ReviewDetailView.as_view(), name='detail'),
    path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='delete'),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
{% block html %}
<html lang="en">
{% block head %}
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<script src="https://kit.fontawesome.com/7911ffdd30.js" crossorigin="anonymous"></script>
<link rel="shortcut icon" type="image/png"
  href="{% static 'images/favicon.png' %}">
<title>{% block title %}{% endblock %} | Play2Learn</title>
{% block javascript %}{% endblock %}{% endblock %}
</head>
<body>
{% block body %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'pages:homepage' %}">
      <h1 style="text-indent: 0.5em;">Play2Learn</h1>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent" aria-expanded="false"
      aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pages:homepage' %}">Home 
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item"></li>
          <a class="nav-link" href="{% url 'reviews:list' %}">Reviews</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'games:leaderboard' %}">Leaderboard</a>
        </li>      
        {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
          </li>
        {% else %}
          <li class="nav-item"></li>
            <a class="nav-link" href="{% url 'games:game-scores' %}">My Game Scores</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
              role="button" data-bs-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              Me
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'my-account' %}">
                My Account
              </a>
              <div class="dropdown-divider"></div>
              <form method="post" action="{% url 'account_logout' %}">
                {% csrf_token %}
                <button class="btn dropdown-item">Log out</button>
              </form>
            </div>
          </li>  
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
                role="button" data-bs-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                Games
              </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="http://127.0.0.1:8000/anagram-hunt/">
                Anagram Hunt
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="http://127.0.0.1:8000/math-facts/">
                Math Facts
              </a>
            </div>
          </li>        
        {% endif %}
      </ul>
    </div>
  </nav>
</header>
<main class="m-4 pb-5">
  {% if messages %}
    <ul>
      {% for message in messages %}
      <div class="alert message{{ message.tags }} alert-dismissible" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    </ul>
  {% endif %}
  {% block main %}<h2>Welcome!</h2>{% endblock %}
</main>
<footer class="fixed-bottom bg-light row">
    <div class="col">
      <div class="float-end m-1 me-2">Copyright &copy; 2024 Play2Learn.</div>
      <nav>
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact:app' %}">Contact Us</a>
          </li>
          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="/admin/">Admin</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </nav>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>
{% endblock %}

templates/_base_vue.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock %}</title>
<!-- Bootstrap CSS CDN-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script></head>
<body>
  {% block main %}<input hidden="true" id="game_user" value="{{ user.username }}">{% endblock %}
  <div id="app"></div>
  <!-- Bootstrap JS CDN -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/anagram-hunt.html
{% extends "_base_vue.html" %}

{% block title %}Anagram Hunt{% endblock %}
{% block main %}
  <h1>Anagram Hunt</h1>
  {{ block.super }}
{% endblock %} 

templates/game-scores.html
{% extends "_base.html" %}

{% block title %}Game Scores{% endblock %}
{% block main %}
  <h1>Game Scores - {{ user.username }} </h1>
  <h2>Anagram Hunt</h2>
  <ol>
    {% for score in anagram_scores %}
        <li>SCORE: {{score.score}} <br> WORD LENGTH: {{score.word_length}} <br> DATE: {{score.created}}</li>
    {% endfor %}
  </ol>
  <h2>Math Facts</h2>
  <ol>
    {% for score in math_scores %}
        <li>SCORE: {{score.score}} <br> OPERATION: {{score.operation}} <br> MAX NUMBER: {{score.max_number}} <br> DATE: {{score.created}}</li>
    {% endfor %}
  </ol>
{% endblock %}

templates/leaderboard.html
{% extends "_base.html" %}

{% block title %}Leaderboard{% endblock %}
{% block main %}
  <h1>Leaderboard</h1>
  <h2>Anagram Hunt</h2>
  <ol>
    {% for score in anagram_scores %}
    <li>SCORE: {{score.score}} <br> USERNAME: {{score.user_name}} <br> WORD LENGTH: {{score.word_length}} <br/> DATE: {{score.created}}</li>
    {% endfor %}
  </ol>
  <h2>Math Facts</h2>
  <ol>
    {% for score in math_scores %}
        <li>SCORE: {{score.score}} <br> USERNAME: {{score.user_name}} <br> OPERATION: {{score.operation}} <br> MAX NUMBER: {{score.max_number}} <br/> DATE: {{score.created}}</li>
    {% endfor %}
  </ol>
{% endblock %}

templates/math-facts.html
{% extends "_base_vue.html" %}

{% block title %}Math Facts{% endblock %}
{% block main %}
  <h1>Math Facts</h1>
  {{ block.super }}
{% endblock %}